services:
  traefik:
    image: traefik:v3.2.3
    ports:
      - 80:80
      # Expose traefik dashboard on port 8080. Dashboard is enabled by passing `--api.insecure=true` option.
      - 8080:8080
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      # Allow traefik to listen to docker events.
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    deploy:
      replicas: 2
    image: traefik/whoami:v1.10
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
