services:
  docker-socket-proxy:
    environment:
      CONTAINERS: 1
    image: tecnativa/docker-socket-proxy:0.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  grafana:
    image: grafana/grafana-oss:11.4.0
    volumes:
      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana-data-sources.yml:/etc/grafana/provisioning/datasources/grafana-data-sources.yml
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./traefik-dashboard.json:/etc/grafana/provisioning/dashboards/traefik-dashboard.json
  nginx:
    image: nginx:1.27.3
  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  traefik:
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 5s
      test:
        - CMD
        - traefik
        - healthcheck
      timeout: 1s
    image: traefik:v3.2.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml
      - ./request-id:/plugins-local/src/github.com/ofadiman/request-id
      - ./tls-certificate.pem:/etc/traefik/tls-certificate.pem
      - ./tls-key.pem:/etc/traefik/tls-key.pem
      - ./traefik.yaml:/etc/traefik/traefik.yaml
  whoami:
    deploy:
      replicas: 2
    image: traefik/whoami:v1.10
