services:
  nginx:
    image: nginx:1.27.3
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`nginx.docker.localhost`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
  traefik:
    image: traefik:v3.2.3
    ports:
      - 80:80
      - 443:443
      # Expose traefik dashboard on port 8080. Dashboard is enabled by passing `--api.insecure=true` option.
      - 8080:8080
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      # Allow traefik to listen to docker events.
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    deploy:
      replicas: 2
    image: traefik/whoami:v1.10
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
