accessLog:
  filters:
    statusCodes:
      - "404"
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: webSecure
  webSecure:
    address: :443
experimental:
  localPlugins:
    requestId:
      moduleName: github.com/ofadiman/request-id
log:
  level: INFO
metrics:
  # Prometheus metrics are available at http://localhost:8080/metrics.
  prometheus: {}
ping: {}
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
