api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: webSecure
  webSecure:
    address: :443
log:
  level: INFO
accessLog:
  filters:
    statusCodes:
      - "404"
providers:
  docker:
    exposedByDefault: false
