api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: webSecure
  webSecure:
    address: :443
  webFourTwenty:
    address: :420
log:
  level: INFO
providers:
  docker:
    exposedByDefault: false
    httpClientTimeout: "10"
    useBindPortIP: true
