accessLog:
  filters:
    statusCodes:
      - "404"
api:
  dashboard: true
  insecure: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: webSecure
  webSecure:
    address: :443
    http:
      encodeQuerySemicolons: true
experimental:
  localPlugins:
    requestId:
      moduleName: github.com/ofadiman/request-id
log:
  level: INFO
metrics:
  # Prometheus metrics are available at http://localhost:8080/metrics.
  prometheus: {}
ping: {}
providers:
  docker:
    endpoint: tcp://docker-socket-proxy:2375
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
serversTransport:
  forwardingTimeouts:
    dialTimeout: 5s
    idleConnTimeout: 10s
    responseHeaderTimeout: 5s
